name: stock-prices-daily

on:
  workflow_dispatch:
  schedule:
    # Runs the workflow daily at midnight UTC
    - cron: '0 0 * * *'


jobs:
  schedule_pipelines:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      contents: write

    steps:
      - name: checkout repo content
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - name: install python packages
        working-directory: notebooks
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check API Key
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: |
          if [ -z "$HOPSWORKS_API_KEY" ]; then
            echo "HOPSWORKS_API_KEY is not set"
            exit 1
          else
            echo "HOPSWORKS_API_KEY is set"
          fi
    
      - name: execute python workflows from bash script
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: |
          cd notebooks
          jupyter nbconvert --to notebook --execute 2_stockpred_feature_pipeline.ipynb
          jupyter nbconvert --to notebook --execute 4_stockpred_batch_inference.ipynb

      - name: github pages publish
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Stockprices Dashboard published"
          commit_options: '--no-verify --signoff'

          # file_pattern: 'notebooks/img/* notebooks/_includes/*' 

          repository: .

          status_options: '--untracked-files=no'

          skip_dirty_check: true

          skip_fetch: true

          skip_checkout: true

          push_options: '--force'
